package com.fupinyou.shanci.shanciapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CET4TABLE.
 */
public class Word {

    private Long id;
    private String wordcontent;
    private String sentence;

    public Word() {
    }

    public Word(Long id) {
        this.id = id;
    }

    public Word(Long id, String wordcontent, String sentence) {
        this.id = id;
        this.wordcontent = wordcontent;
        this.sentence = sentence;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWordcontent() {
        return wordcontent;
    }

    public void setWordcontent(String wordcontent) {
        this.wordcontent = wordcontent;
    }

    public String getSentence() {
        return sentence;
    }

    public void setSentence(String sentence) {
        this.sentence = sentence;
    }

}
